feat: add install with go support, fix flags
sigstore/cosign-installer pull request #48
Opened 2022-01-07 13:52 UTC by developer-guy

#### Summary

feat: add install with go support, fix flags

#### Ticket Link

Fixes #45 

#### Release Note

```release-note
feat: add install with go support, fix flags
```

2022-01-07 14:27 UTC, cpanato requested changes
looks cool!
can you add some doc in the readme?

2022-01-07 14:32 UTC, developer-guy commented
> looks cool! can you add some doc in the readme?
@dentrax and @necatican can you please help me with this folks? ✌️

2022-01-07 15:52 UTC, bobcallaway commented on action.yml
> +          echo "INFO: installing cosign via go install from its main version"
```suggestion
          log_info "installing cosign via 'go install' from its main version"
```

2022-01-09 09:46 UTC, developer-guy commented on action.yml
> +          echo "INFO: installing cosign via go install from its main version"
thanks for the tip @bobcallaway ✌️

2022-01-09 09:52 UTC, developer-guy commented
> looks cool! can you add some doc in the readme?

We(w/@dentrax @necatican)'ve completed the documentation of our new feature. Thank you @cpanato ✌️

2022-01-10 13:34 UTC, bobcallaway commented on action.yml
> +          go install github.com/sigstore/cosign/cmd/cosign@main
while this would build & install the binary into the current value of`$GOBIN`, it doesn't respect the `install-dir` input parameter for this action

2022-01-10 16:25 UTC, developer-guy commented on action.yml
> +          go install github.com/sigstore/cosign/cmd/cosign@main
Ah, yes! Thank you, @bobcallaway, for bringing it to my attention  🙋🏻‍♂️ Do you recommend adding this to the information message?

2022-01-12 19:10 UTC, bobcallaway commented on action.yml
> +          go install github.com/sigstore/cosign/cmd/cosign@main
why not just set `GOBIN=${{ inputs.install-dir }}` ahead of the `go install` command, or copy/symlink it after its done?

2022-01-18 11:21 UTC, developer-guy commented on action.yml
> +          go install github.com/sigstore/cosign/cmd/cosign@main
amazing idea @bobcallaway, thank you for bringing it to my attention. I've updated the GA according to your feedback.

2022-01-18 12:38 UTC, bobcallaway reviewed
one comment otherwise LGTM

2022-01-18 12:38 UTC, bobcallaway commented on action.yml
> +          echo "${{ inputs.install-dir }}" >> $GITHUB_PATH
```suggestion
```
this is done below in a platform-independent way so i think you can remove this line

2022-01-18 13:06 UTC, bobcallaway approved these changes
thanks @developer-guy :)

2022-01-18 15:24 UTC, cpanato approved these changes

2022-01-18 15:25 UTC, merged